### ISSUE TITLE
Add Packagist webhook

### ISSUE THREAD

**Issue by beaver-dev** [featherbb/private-messages#1]
Hi,
To finalize packagist integration : after committing the work you've done lately and creating a new tag, you can go to https://github.com/featherbb/private-messages/settings/hooks/new?service=packagist, add your Packagist token and username, and submit the form.
More details here => https://packagist.org/about#how-to-update-packages

**Comment by adaur** [comment]
"Okay, that hook was successfully created. "

**Comment by beaver-dev** [comment]
Great ! I'll let you know when the marketplace has the minimal structure to begin working on it, for the moment I only integrated some FeatherBB features and check if we could use Slim v3 for it.
If this plugin really updates after adding a new tag, it will confirm we can use this method for all future plugins :)
